codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  notify:
    slack:
      default:
        url: "secret:LYkSVa7ylP5lIC31WpDt1Ja2Uq3Fg0HTaouEEnXT1VrbuAgQ+JP7mrkqmaVQEefvl6r9BevB8d/AGqE8v7YkEMcFevwsiUw5vK0VSMlBCBKUCjDZMAv32E836rtrfTCj7yQnwoMQ96eEx2XRBstN7Qe6T8Emk4cWCuvFeatdqna7yLKD8m81jrk2DceOPAq36CFuygyjNwQsnTe9B6hGrW995e5ovO24cU9TFvCdXR0="
        threshold: null
        attachments: "sunburst, diff"

  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "*/di/*" #dependency injections
  - "**/*Impl*"
