codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  notify:
    slack:
      default:
        url: "https://discordapp.com/api/webhooks/552199916751945758/cgv3MMxLe217B7Q1Qx2KWmIWNYZy2IjzagbZ4QgTcDogevQ9_t0kLQsfjiaZ69tXfdkf/slack"

  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "*/di/*" #dependency injections
